/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNotify: typeof import('./components/AppNotify.vue')['default']
    BackToTopButton: typeof import('./components/BackToTopButton.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    MentionText: typeof import('./components/MentionText.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NTag: typeof import('naive-ui')['NTag']
    OfficialAnnouncementCarousel: typeof import('./components/OfficialAnnouncementCarousel.vue')['default']
    PostAiCardLine: typeof import('./components/PostAiCardLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarLeft: typeof import('./components/SidebarLeft.vue')['default']
    SidebarRight: typeof import('./components/SidebarRight.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}
